name = "architektura, budownictwo, zagospodarowanie przestrzenne"
question = "Sprawa dotyczy: "
end = True
options = {
    0: "Informacja o aktualnym etapie załatwiania sprawy w Wydziale Architektury i Budownictwa",
    1: "Odstępstwo od przepisów techniczno – budowlanych",
    2: "Opiniowanie formy i lokalizacji szyldu, autoreklamy, nośnika reklamowego, ogródka gastronomicznego, obiektu małej architektury, innego obiektu",
    3: "Pozwolenie na budowę",
    4: "Pozwolenie na rozbiórkę",
    5: "Przeniesienie decyzji o warunkach zabudowy na rzecz innej osoby",
    6: "Przeniesienie pozwolenia na budowę na rzecz innej osoby",
    7: "Przeniesienie zgłoszenia budowy budynku mieszkalnego, sieci, stacji transformatorowej na rzecz innej osoby",
    8: "Rejestracja dziennika budowy/rozbiórki",
    9: "Udostępnianie akt spraw aktualnie rozpatrywanych w Wydziale Architektury i Budownictwa",
    10: "Udostępnianie akt zakończonych postępowań oraz wydanie uwierzytelnionych kopii dokumentów w Wydziale Architektury i Budownictwa",
    11: "Ustalenie czy na danym terenie obowiązuje miejscowy plan zagospodarowania przestrzennego",
    12: "Ustalenie lokalizacji inwestycji celu publicznego",
    13: "Ustalenie numerów porządkowych (adresów) / zaświadczenie o numerze porządkowym",
    14: "Ustalenie warunków zabudowy",
    15: "Uzupełnienie wniosku",
    16: "Wgląd do miejscowego planu zagospodarowania przestrzennego",
    17: "Wniosek o sporządzenie/zmianę miejscowego planu zagospodarowania przestrzennego",
    18: "Wniosek o zmianę studium uwarunkowań i kierunków zagospodarowania przestrzennego Wrocławia",
    19: "Wycofanie wniosku",
    20: "Wypis i wyrys z obowiązującego miejscowego planu zagospodarowania przestrzennego",
    21: "Wypis i wyrys ze Studium uwarunkowań i kierunków zagospodarowania przestrzennego Wrocławia",
    22: "Zaświadczenia o samodzielności lokali",
    23: "Zaświadczenie do wniosku o przyznanie dodatku mieszkaniowego",
    24: "Zaświadczenie o braku miejscowego planu zagospodarowania przestrzennego",
    25: "Zaświadczenie o ostateczności decyzji wydanej w Wydziale Architektury i Budownictwa",
    26: "Zaświadczenie potwierdzające fakty lub stan prawny wynikający z posiadanych dokumentów i danych w Wydziale Architektury i Budownictwa",
    27: "Zezwolenie na realizację inwestycji drogowej",
    28: "Zgłoszenie  budowy sieci, stacji transformatorowej",
    29: "Zgłoszenie budowy lub przebudowy budynku mieszkalnego jednorodzinnego",
    30: "Zgłoszenie budowy obiektów lub wykonania robót budowlanych niewymagających pozwolenia na budowę",
    31: "Zgłoszenie rozbiórki obiektów budowlanych niewymagających pozwolenia na rozbiórkę",
    32: "Zgłoszenie zmiany sposobu użytkowania obiektu budowlanego lub jego części",
    33: "Zmiana decyzji o pozwoleniu na budowę",
    34: "Zmiana decyzji o warunkach zabudowy",
}
