name = "komunikacja, transport"
question = "Sprawa dotyczy: "
end = True
options = {
    0	: 'Identyfikatory zezwalające na dojazd do cmentarzy w okresie świąt zmarłych - w celach zaopatrzeniowych ',
    1	: 'Interwencja mieszkańców w sprawie organizacji ruchu w mieście – propozycje zmian zgłoszone przez mieszkańców ',
    2	: 'Licencja na wykonywanie krajowego transportu drogowego osób pojazdami samochodowymi do 9 miejsc ',
    3	: 'Licencja na wykonywanie krajowego transportu drogowego w zakresie przewozu osób taksówką ',
    4	: 'Licencja na wykonywanie transportu drogowego w zakresie pośrednictwa przy przewozie rzeczy',
    5	: 'Odbiór pojazdu usuniętego z drogi ',
    6	: 'Opiniowanie geometrii drogi oraz obsługi komunikacyjnej obiektów ',
    7	: 'Organizacja na terenie Gminy Wrocław transportu osób mających trudności w samodzielnym dotarciu do punktów szczepień przeciwko wirusowi SARS-CoV-2',
    8	: 'Projekt zastępczej lub docelowej organizacji ruchu',
    9	: 'Prowadzenie Ośrodka Szkolenia Kierowców',
    10	: 'Wpis do ewidencji instruktorów nauki jazdy ',
    11	: 'Wpis do ewidencji podmiotów prowadzących szkolenie (nauka jazdy)',
    12	: 'Wpis do ewidencji wykładowców nauki jazdy',
    13	: 'Wpis do rejestru przedsiębiorców prowadzących ośrodki szkolenia kierowców ',
    14	: 'Wpis do rejestru przedsiębiorców prowadzących stacje kontroli pojazdów ',
    15	: 'Wydanie poświadczenia potwierdzającego spełnianie dodatkowych wymagań przedsiębiorcy prowadzącego ośrodki szkolenia kierowców',
    16	: 'Wydawanie lub zmiana uprawnień diagnosty do wykonywania badań technicznych pojazdów ',
    17	: 'Wygaśnięcie licencji na wykonywanie krajowego transportu drogowego w zakresie przewozu osób taksówką w związku z likwidacją działalności/zrzeczeniem się licencji',
    18	: 'Zasady wjazdu do Wrocławia pojazdów ciężarowych powyżej 18 t DMC',
    19	: 'Zasady wydawania i użytkowania identyfikatorów B-1 uprawniających do wjazdu w strefę objętą zakazem ruchu na terenie Miasta Wrocławia',
    20	: 'Zaświadczenie na przewozy drogowe na potrzeby własne',
    21	: 'Zaświadczenie na wykonywanie publicznego transportu zbiorowego ',
    22	: 'Zezwolenie na przejazd pojazdów nienormatywnych',
    23	: 'Zezwolenie na przeprowadzenie imprezy z wykorzystaniem dróg w sposób szczególny',
    24	: 'Zezwolenie na wykonywanie przewozów regularnych i regularnych specjalnych w krajowym transporcie drogowym osób ',
    25	: 'Zezwolenie na wykonywanie zawodu przewoźnika drogowego',
}
