name = "nieruchomości"
question = "Sprawa dotyczy: "

options = {
    0	: 'Bonifikata od opłat rocznych z tytułu użytkowania wieczystego nieruchomości stanowiących własność Gminy Wrocław (procedura realizowana przez WNK)	',
    1	: 'Czasowe udostępnianie gruntów Gminy Wrocław z przeznaczeniem na inwestycje liniowe',
    2	: 'Czasowe udostępnianie gruntów Skarbu Państwa',
    3	: 'Czasowe udostępnienie gruntów Gminy Wrocław z przeznaczeniem na zaplecze budowy',
    4	: 'Informacja o wysokości opłaty rocznej z tytułu użytkowania wieczystego gruntu Gminy Wrocław	',
    5	: 'Informacja o wysokości opłaty rocznej z tytułu użytkowania wieczystego gruntu Skarbu Państwa	',
    6	: 'Oddawanie nieruchomości stanowiących własność Gminy Wrocław w trwały zarząd',
    7	: 'Oddawanie nieruchomości stanowiących własność Skarbu Państwa w trwały zarząd',
    8	: 'Odszkodowania za grunty wydzielone pod drogi publiczne (gminne i powiatowe)	',
    9	: 'Pozyskanie w najem gminnego lokalu użytkowego w trybie bezprzetargowym przez organizację pozarządową	',
    10	: 'Pozyskanie w użyczenie gminnego lokalu użytkowego przez organizację kombatancką	',
    11	: 'Przedłużenie terminu prawa użytkowania wieczystego nieruchomości stanowiących własność Gminy Wrocław	',
    12	: 'Przedłużenie terminu prawa użytkowania wieczystego nieruchomości stanowiących własność Skarbu Państwa	',
    13	: 'Przedłużenie terminu zagospodarowania nieruchomości stanowiącej własność Gminy Wrocław oddanej w użytkowanie wieczyste	',
    14	: 'Przedłużenie terminu zagospodarowania nieruchomości stanowiącej własność Skarbu Państwa oddanej w użytkowanie wieczyste	',
    15	: 'Przekształcenie prawa użytkowania wieczystego gruntów mieszkaniowych Skarbu Państwa	',
    16	: 'Przekształcenie prawa użytkowania wieczystego gruntu zabudowanego na cele mieszkaniowe w prawo własności tego gruntu - na podstawie przepisów ustawy z dnia 20 lipca 2018r. o przekształceniu prawa użytkowania wieczystego gruntów zabudowanych na cele mieszkaniowe prawo własności tych gruntów (procedura realizowana przez WNS)	',
    17	: 'Przekształcenie prawa użytkowania wieczystego gruntu zabudowanego na cele mieszkaniowe w prawo własności tego gruntu - procedura realizowana na podstawie przepisów ustawy z dnia 20 lipca 2018 r. o przekształceniu prawa użytkowania wieczystego gruntów zabudowanych na cele mieszkaniowe prawo własności tych gruntów	',
    18	: 'Przekształcenie prawa użytkowania wieczystego w prawo własności nieruchomości stanowiących własność Gminy Wrocław	',
    19	: 'Przekształcenie prawa użytkowania wieczystego w prawo własności nieruchomości stanowiących własność Skarbu Państwa	',
    20	: 'Przekształcenie wieczystego użytkowania w prawo własności na działkach zabudowanych zespołami garażowymi	',
    21	: 'Sprzedaż gminnych mieszkań i lokali użytkowych w drodze przetargu',
    22	: 'Sprzedaż gruntów i budynków w drodze przetargu',
    23	: 'Sprzedaż w trybie bezprzetargowym na rzecz użytkownika wieczystego nieruchomości stanowiącej własność Gminy Wrocław',
    24	: 'Sprzedaż w trybie bezprzetargowym na rzecz użytkownika wieczystego nieruchomości stanowiącej własność Skarbu Państwa',
    25	: 'Szczegółowe zasady, sposób i tryb umarzania, odraczania lub rozkładania na raty spłaty należności pieniężnych mających charakter cywilnoprawny przypadających Skarbowi Państwa z tytułu opłat za użytkowanie wieczyste	',
    26	: 'Ujednolicenie terminów prawa użytkowania wieczystego nieruchomości stanowiących własność Gminy Wrocław',
    27	: 'Ujednolicenie terminów prawa użytkowania wieczystego nieruchomości stanowiących własność Skarbu Państwa',
    28	: 'Ustanowienie służebności gruntowej	',
    29	: 'Ustanowienie służebności przesyłu	',
    30	: 'Wniosek o dokonanie aktualizacji opłaty rocznej z tytułu użytkowania wieczystego gruntów stanowiących własność Skarbu Państwa	',
    31	: 'Wydzierżawianie gruntów Gminy Wrocław',
    32	: 'Wydzierżawianie gruntów Skarbu Państwa	',
    33	: 'Zezwolenie na czasowe zajęcie gruntów Gminy Wrocław osobom prowadzącym działalność rozrywkową i kulturalną',
    34	: 'Zezwolenie na czasowe zajęcie gruntów Skarbu Państwa osobom prowadzącym działalność rozrywkową i kulturalną',
    35	: 'Zgłoszenie zmiany adresu do korespondencji (sprawy związane z nieruchomościami Skarbu Państwa)	',
    36	: 'Zmiana celu użytkowania wieczystego gruntu Skarbu Państwa	',
}
