name = "podatki, opłaty"
question = "Sprawa dotyczy: "
end = True
options = {
    0	: 'Deklaracja na podatek od nieruchomości',
    1	: 'Duplikat faktury VAT lub duplikat faktury korygującej VAT',
    2	: 'Interpretacja przepisów prawa podatkowego w indywidualnej sprawie',
    3	: 'Korekta danych na fakturze wystawionej przez WPO - błędy dot. ceny, stawki lub kwoty podatku VAT',
    4	: 'Korekta danych na fakturze wystawionej przez WPO - błędy formalne dot. nabywcy',
    5	: 'Opłata skarbowa – złożenie wniosku o zwrot opłaty skarbowej',
    6	: 'Opłata za gospodarowanie odpadami komunalnymi - złożenie deklaracji (osoby fizyczne)',
    7	: 'Opłata za gospodarowanie odpadami komunalnymi - złożenie deklaracji (osoby prawne)',
    8	: 'Opłata za zmniejszenie naturalnej retencji terenowej',
    9	: 'Podatek leśny – złożenie deklaracji (osoby prawne)',
    10	: 'Podatek leśny – złożenie informacji (osoby fizyczne)',
    11	: 'Podatek od nieruchomości - złożenie deklaracji (osoby prawne)',
    12	: 'Podatek od nieruchomości - złożenie informacji IN-1 (osoby fizyczne)',
    13	: 'Podatek od środków transportowych - złożenie deklaracji',
    14	: 'Podatek rolny - złożenie informacji (osoby fizyczne)',
    15	: 'Podatek rolny – złożenie deklaracji (osoby prawne)',
    16	: 'Pomoc publiczna dla przedsiębiorców',
    17	: 'Rozpatrywanie wniosków z zakresu kar i opłat za parkowanie w strefie płatnego postoju oraz za zajęcie pasa drogowego',
    18	: 'Udzielanie ulg w spłacie zobowiązań, dotyczących opłat rocznych z tytułu użytkowania wieczystego nieruchomości gruntowych oraz z tytułu  przekształcenia prawa użytkowania wieczystego gruntów zabudowanych na cele mieszkaniowe w prawo własności tych gruntów, stanowiących własność  Skarbu Państwa  – dotyczy wniosków złożonych nie później niż 14 dni przed upływem terminu płatności',
    19	: 'Ulgi w spłacie niektórych należności  cywilnoprawnych przypadających Gminie Wrocław',
    20	: 'Ulgi w spłacie niepodatkowych należności publicznoprawnych z tytułu renty planistycznej, opłaty adiacenckiej, mandatów karnych SM oraz kosztów egzekucyjnych',
    21	: 'Ulgi w spłacie opłaty za gospodarowanie odpadami komunalnymi',
    22	: 'Ulgi w spłacie podatków i opłat lokalnych, podatku rolnego, leśnego, opłaty skarbowej',
    23	: 'Zajęcie stanowiska w przedmiocie udzielenia ulgi w spłacie zobowiązań podatkowych w zakresie podatków pobieranych przez US, tj. podatek od czynności cywilnoprawnych, od spadków i darowizn, zryczałtowany podatek dochodowy - karta podatkowa',
    24	: 'Zaświadczenie o figurowaniu/niefigurowaniu w ewidencji podatkowej',
    25	: 'Zaświadczenie o niezaleganiu w opłacie za użytkowanie wieczyste gruntu lub stwierdzające stan zaległości',
    26	: 'Zaświadczenie o niezaleganiu w podatkach lub stwierdzające stan zaległości',
    27	: 'Zaświadczenie o niezaleganiu/stwierdzającego stan zaległości w opłacie za gospodarowanie odpadami komunalnymi',
    28	: 'Zaświadczenie o okresie płacenia składki na Fundusz Emerytalny Rolników Fundusz/Ubezpieczenia Społecznego Rolników',
    29	: 'Zaświadczenie o okresie posiadania działów specjalnych produkcji rolnej (dotyczy okresu do 31.12.1984 r.)',
    30	: 'Zaświadczenie o pomocy de minimis dla Zakładu Pracy Chronionej',
    31	: 'Zaświadczenie o posiadanych/nieposiadanych powierzchniach użytków rolnych w hektarach fizycznych i przeliczeniowych',
    32	: 'Zaświadczenie o powierzchniach zgłoszonych do opodatkowania podatkiem od nieruchomości',
    33	: 'Zaświadczenie o wysokości zaległości podatkowych zbywającego',
    34	: 'Zaświadczenie o wysokości zobowiązań spadkodawcy',
    35	: 'Zaświadczenie w celu wykreślenia hipoteki przymusowej z tytułu przekształcenia prawa wieczystego użytkowania w prawo własności',
    36	: 'Zaświadczenie w celu wykreślenia hipoteki umownej/kaucyjnej z tytułu wykupu nieruchomości',
    37	: 'Zmiana danych osobowych lub adresowych klienta',
    38	: 'Zwolnienie od podatku od nieruchomości w związku z inwestycją w instalację fotowoltaiczną, pompę ciepła, rekuperator, gruntowy wymiennik ciepła, kolektor słoneczny',
    39	: 'Zwrot błędnie dokonanych wpłat',
    40	: 'Zwrot nadpłaty - na rachunek bankowy lub adres domowy',
    41	: 'Zwrot nadpłaty - odbiór środków w gotówce',
    42	: 'Zwrot nadpłaty - przekazanie nadpłaty na inne zobowiązania wobec gminy',
    43	: 'Zwrot nadpłaty na rachunek bankowy, adres domowy lub inne zobowiązanie wobec Gminy',
    44	: 'Zwrot podatku akcyzowego zawartego w cenie oleju napędowego',
}
