name = "rejestracja pojazdów"
question = "Sprawa dotyczy: "

options = {
    0	: 'Czasowe wycofanie pojazdu z ruchu',
    1	: 'Dodatkowa tablica rejestracyjna do oznaczenia bagażnika oraz jej wtórnik',
    2	: 'Dowód rejestracyjny - odbiór nowego (wyprodukowanego) dokumentu',
    3	: 'Dowód rejestracyjny - uzyskanie kserokopii dowodu rejestracyjnego',
    4	: 'Dowód rejestracyjny - wpis adnotacji VAT/PIT/CIT',
    5	: 'Dowód rejestracyjny - wydanie/zwrot dowodu zatrzymanego przez policję',
    6	: 'Dowód rejestracyjny - wydawanie duplikatu (wtórnika)',
    7	: 'Dowód rejestracyjny - zmiana stanu faktycznego, wymagająca zmiany danych zawartych w dowodzie rejestracyjnym (np. adres, nazwisko, rodzaj pojazdu, dane techniczne)',
    8	: 'Dowód rejestracyjny – wymiana z powodu braku miejsca na kolejne wpisy terminów badania technicznego',
    9	: 'Nadawanie cech identyfikacyjnych na nadwoziu i podwoziu (ramie) oraz wykonanie tabliczki znamionowej zastępczej',
    10	: 'Profesjonalna rejestracja pojazdu',
    11	: 'Rejestracja motoroweru i motocykla',
    12	: 'Rejestracja pojazdu - czasowa',
    13	: 'Rejestracja pojazdu - pojazd fabrycznie nowy',
    14	: 'Rejestracja pojazdu - pojazd zabytkowy',
    15	: 'Rejestracja pojazdu - pojazd zakupiony i zarejestrowany w kraju',
    16	: 'Rejestracja pojazdu – pojazd sprowadzony z zagranicy',
    17	: 'Umorzenie postępowania w sprawie rejestracji pojazdów',
    18	: 'Wtórnik karty pojazdu',
    19	: 'Wtórnik nalepki kontrolnej na szybę',
    20	: 'Wtórnik tablic (tablicy) rejestracyjnych - wydawany z powodu kradzieży, zagubienia lub zniszczenia tablic',
    21	: 'Wtórnik znaku legalizacyjnego',
    22	: 'Wykreślenie z dowodu rejestracyjnego banku będącego współwłaścicielem pojazdu',
    23	: 'Wyrejestrowanie pojazdu - po kradzieży',
    24	: 'Wyrejestrowanie pojazdu - złomowanie',
    25	: 'Zaświadczenia potwierdzające dane zawarte w dowodzie rejestracyjnym lub w karcie pojazdu',
    26	: 'Zawiadomienie o dokonaniu montażu instalacji przystosowującej pojazd do zasilania gazem oraz przystosowaniu pojazdu do ciągnięcia przyczepy („Hak”)',
    27	: 'Zbycie/nabycie pojazdu - zawiadomienie',
    28	: 'Zmiana rodzaju pojazdu',
}
