name = "środowisko, rolnictwo"
question = "Sprawa dotyczy: "

options = {
    0	: 'Decyzja o dopuszczalnym poziomie hałasu',
    1	: 'Decyzja o środowiskowych uwarunkowaniach dla planowanego przedsięwzięcia mogącego potencjalnie znacząco oddziaływać na środowisko',
    2	: 'Decyzja o środowiskowych uwarunkowaniach dla planowanego przedsięwzięcia mogącego zawsze znacząco oddziaływać na środowisko',
    3	: 'Dofinansowanie w ramach Programu usuwania azbestu i wyrobów zawierających azbest z terenu miasta Wrocławia',
    4	: 'Gromadzenie, archiwizowanie i udostępnianie informacji geologicznej',
    5	: 'Informacja o wyrobach zawierających azbest',
    6	: 'Interwencja w sprawie uciążliwego hałasu',
    7	: 'Karty wędkarskie lub karty łowiectwa podwodnego',
    8	: 'Poświadczenie oświadczenia o osobistym prowadzeniu gospodarstwa rolnego',
    9	: 'Pozwolenie na wprowadzanie gazów lub pyłów do powietrza',
    10	: 'Pozwolenie na wytwarzanie odpadów',
    11	: 'Pozwolenie zintegrowane',
    12	: 'Przekazanie innej dokumentacji geologicznej',
    13	: 'Rejestr działalności regulowanej w zakresie odbierania odpadów komunalnych od właścicieli nieruchomości na terenie miasta Wrocławia',
    14	: 'Rejestracja jachtów i innych jednostek pływających o długości do 24m',
    15	: 'Skreślenie z rejestru zwierząt lub zmiana danych w rejestrze',
    16	: 'Udostępnianie informacji o środowisku',
    17	: 'Udostępnianie kompostowników',
    18	: 'Udzielenie koncesji na wydobywanie kopalin nie objętych własnością górniczą przypadku gdy: obszar udokumentowanego złoża nie przekracza 2ha; wydobycie kopaliny ze złoża w roku kalendarzowym nie przekroczy 20 000 m3; działalność będzie prowadzona metodą odkrywkową oraz bez użycia środków strzałowych',
    19	: 'Uznanie drzewa/krzewu za złom/wywrot',
    20	: 'Wpis do rejestru zwierząt',
    21	: 'Wyłączenie z produkcji rolnej nieruchomości',
    22	: 'Zaświadczenie o objęciu gruntu uproszczonym planem urządzenia lasu lub decyzją, o której mowa w art. 19 ust. 3 ustawy o lasach',
    23	: 'Zaświadczenie potwierdzające posiadanie gospodarstwa rolnego – wliczanie pracy w indywidualnym gospodarstwie rolnym do pracowniczego stażu pracy',
    24	: 'Zatwierdzanie dokumentacji geologicznych',
    25	: 'Zatwierdzanie projektu robót geologicznych (z zakresu geologii inżynierskiej i hydrogeologii)',
    26	: 'Zezwolenie na hodowanie lub utrzymywanie chartów rasowych lub ich mieszańców',
    27	: 'Zezwolenie na prowadzenie działalności w zakresie opróżniania zbiorników bezodpływowych i transportu nieczystości ciekłych',
    28	: 'Zezwolenie na prowadzenie hodowli lub utrzymywanie psa rasy uznawanej za agresywną',
    29	: 'Zezwolenie na przetwarzanie odpadów',
    30	: 'Zezwolenie na uczestnictwo we wspólnotowym handlu uprawnieniami do emisji do powietrza gazów cieplarnianych',
    31	: 'Zezwolenie na uprawę maku lub konopi włóknistych',
    32	: 'Zezwolenie na usunięcie drzew i krzewów',
    33	: 'Zezwolenie na zbieranie odpadów',
    34	: 'Zezwolenie w zakresie ochrony przed bezdomnymi zwierzętami',
    35	: 'Zezwolenie w zakresie prowadzenia grzebowisk i spalarni zwłok zwierzęcych i ich części',
    36	: 'Zezwolenie w zakresie prowadzenia schronisk dla bezdomnych zwierząt',
    37	: 'Zgłoszenia instalacji wytwarzających pola elektromagnetyczne',
    38	: 'Zgłoszenie instalacji wprowadzających gazy lub pyły do powietrza, z których emisja nie wymaga pozwolenia',
    39	: 'Zgłoszenie instalacji wprowadzających ścieki do wód lub do ziemi, z których emisja nie wymaga pozwolenia (przydomowe oczyszczalnie ścieków o przepustowości do 5m3 na dobę)',
    40	: 'Zgłoszenie potencjalnego historycznego zanieczyszczenia powierzchni ziemi',
    41	: 'Zgłoszenie projektu prac geologicznych wykonywanych w celu wykorzystania ciepła Ziemi',
    42	: 'Zgłoszenie zamiaru usunięcia drzewa/drzew',
    43	: 'Zmiana dostosowawcza zezwolenia lub pozwolenia obejmującego zbieranie lub przetwarzanie odpadów',
    44	: 'Zwrot opłaty skarbowej',
}
